/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyVirtualCam;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Polygon;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.geometry.Point2D;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class MainFrame extends javax.swing.JFrame {

    public JFrame thisooo = this;

    ImageIcon imageIcon1;
    ImageIcon imageIcon2;

    Timer timer;

    ArrayList<Camera> cameras = new ArrayList();
    ArrayList<ImageIcon> imageIcons = new ArrayList();
    ArrayList<JLabel> jLabels = new ArrayList();

    Optimizer optimizer = new Optimizer();

    boolean isBusy = false;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        cameras.add(new Camera("test1.png", 0, false));
        cameras.add(new Camera("test2.png", 1, false));

        initPanels();
//        imageIcon1 = new ImageIcon();
//        imageIcon2 = new ImageIcon();
//        jLabel1.setIcon(imageIcon1);
//        jLabel2.setIcon(imageIcon2);

        for (int i = 0; i < cameras.size(); i++) {
            cameras.get(i).readImages();
            cameras.get(i).currentSolution = optimizer.initSolution(cameras.get(i));
        }
        timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                if (isBusy == false) {
                    isBusy = true;
                    thisooo.pack();
//                    jLabel2.invalidate();
//                    jLabel2.revalidate();
//                    jLabel2.repaint();
                    for (int i = 0; i < cameras.size(); i++) {
                        {
                            cameras.get(i).readImages();
                            cameras.get(i).currentSolution = optimizer.getCornerPoints(cameras.get(i), cameras.get(i).currentSolution);
                            cameras.get(i).drawDebuggingSolutionPoints(cameras.get(i).currentSolution);
                        }
                        updatePanels();
                        isBusy = false;
                    }
                }
            }
        }, 1000, 10);

    }

    public void initPanels() {
        jPanel4.removeAll();
        jLabels.clear();
        imageIcons.clear();
        for (int i = 0; i < cameras.size(); i++) {
            JPanel jPanel = new javax.swing.JPanel();
            jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(cameras.get(i).webcam.getName()));
            jPanel.setLayout(new java.awt.GridLayout(1, 0));
            JLabel jLabel = new JLabel();
            ImageIcon imageIcon = new ImageIcon();
            jLabels.add(jLabel);
            imageIcons.add(imageIcon);
            jLabel.setIcon(imageIcon);
            jPanel.add(jLabel);
            jPanel4.add(jPanel);
        }

    }

    public void updatePanels() {
        for (int i = 0; i < imageIcons.size(); i++) {
            imageIcons.get(i).setImage(cameras.get(i).originalImage);
        }
        jPanel4.invalidate();
        jPanel4.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel3.add(jLabel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        timer.cancel();
        for (int i = 0; i < cameras.size(); i++) {
            cameras.get(i).webcam.close();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
